#!/bin/bash

# Home Assistant Auto-Install Script
# Automaticky nastaví skripty, NAS a herní servery

echo "🏠 Home Assistant Auto-Install"
echo "==============================="

# Konfigurační proměnné
CONFIG_DIR="/config"
BACKUP_DIR="$CONFIG_DIR/backup_auto_install"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Funkce pro logování
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

# Funkce pro kontrolu chyb
check_error() {
    if [ $? -ne 0 ]; then
        log "❌ CHYBA: $1"
        exit 1
    fi
}

# Vytvoření zálohovacího adresáře
log "Vytvářím zálohu..."
mkdir -p "$BACKUP_DIR"
cp "$CONFIG_DIR/configuration.yaml" "$BACKUP_DIR/configuration.yaml.backup_$TIMESTAMP" 2>/dev/null || true

# Stáhnout nebo vytvořit potřebné soubory
log "Připravuji konfigurační soubory..."

# Vytvoření hlavního configuration.yaml
cat > "$CONFIG_DIR/configuration.yaml" << 'EOF'
# Home Assistant Auto-Configuration
# Generated by auto-install script

default_config:

# Load packages
homeassistant:
  packages: !include_dir_merge_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

# HTTP
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  login_attempts_threshold: 5

# Logging
logger:
  default: info
  logs:
    custom_components.hacs: debug
    homeassistant.components.mqtt: debug

# MQTT
mqtt:
  broker: 127.0.0.1
  port: 1883
  discovery: true
  username: !secret mqtt_username
  password: !secret mqtt_password

# Wake on LAN
wake_on_lan:

# Template sensors
template: !include templates.yaml

# Scripts
script: !include scripts.yaml

# Automation
automation: !include automations.yaml

# Frontend
frontend:
  themes: !include_dir_merge_named themes

# Recorder
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 10

# History
history:

# Logbook
logbook:

# Sun
sun:

# Stream
stream:
EOF

log "Hlavní configuration.yaml vytvořen"

# Vytvoření adresářové struktury
mkdir -p "$CONFIG_DIR/packages"
mkdir -p "$CONFIG_DIR/themes"
mkdir -p "$CONFIG_DIR/www"

# Vytvoření scripts.yaml
cat > "$CONFIG_DIR/scripts.yaml" << 'EOF'
# Automaticky generované skripty
wake_up_routine:
  alias: "Ranní probuzení"
  sequence:
    - service: light.turn_on
      target:
        area_id: loznice
      data:
        brightness_pct: 50
        color_temp: 350
    - delay:
        minutes: 10
    - service: tts.google_translate_say
      data:
        entity_id: media_player.radio
        message: "Dobré ráno, je čas vstávat. Venkovní teplota je {{ states('sensor.outdoor_temperature') }} stupňů."
  mode: single
  icon: mdi:weather-sunny

evening_routine:
  alias: "Večerní režim"
  sequence:
    - service: light.turn_off
      target:
        area_id: obyvaci_pokoj
    - service: light.turn_on
      target:
        entity_id: light.nocni_osvetleni
      data:
        brightness: 10
    - service: climate.set_temperature
      target:
        entity_id: climate.loznice
      data:
        temperature: 18
  mode: single
  icon: mdi:weather-night

turn_on_gaming_pc:
  alias: "Zapnout herní PC"
  sequence:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret gaming_pc_mac
    - delay:
        seconds: 30
    - service: notify.mobile_app_phone
      data:
        title: "Herní PC"
        message: "PC se zapíná, připravte se na hraní!"
  mode: single
  icon: mdi:power

system_repair_cleanup:
  alias: "Vyčištění systému"
  sequence:
    - service: system_log.clear
    - service: recorder.purge
      data:
        keep_days: 7
    - service: persistent_notification.create
      data:
        title: "Systém vyčištěn"
        message: "Všechny nefunkční komponenty byly odstraněny"
  mode: single
  icon: mdi:brush
EOF

log "Scripts.yaml vytvořen"

# Vytvoření templates.yaml
cat > "$CONFIG_DIR/templates.yaml" << 'EOF'
- sensor:
    - name: "Průměrná teplota v domě"
      unique_id: average_house_temperature
      unit_of_measurement: "°C"
      state: >
        {% set temps = [
          states('sensor.living_room_temperature'),
          states('sensor.bedroom_temperature'), 
          states('sensor.kitchen_temperature')
        ] %}
        {% set valid_temps = temps | select('defined') | map('float') | list %}
        {{ (valid_temps | sum / valid_temps | count) | round(1) if valid_temps else 0 }}

    - name: "Počet zapnutých světel"
      unique_id: lights_on_count
      state: >
        {{ states.light | selectattr('state','eq','on') | list | count }}

    - name: "Denní fáze"
      unique_id: day_phase
      state: >
        {% if states('sun.sun') == 'below_horizon' %}
          Noc
        {% else %}
          Den
        {% endif %}

    - name: "Stav zabezpečení domu"
      unique_id: house_security_status
      state: >
        {% if states('alarm_control_panel.house') == 'armed_away' %}
          Aktivní
        {% elif states('lock.front_door') == 'locked' and states('lock.back_door') == 'locked' %}
          Zabezpečeno
        {% else %}
          Otevřeno
        {% endif %}

- binary_sensor:
    - name: "Někdo je doma"
      unique_id: someone_home
      state: >
        {{ states.person | selectattr('state','eq','home') | list | count > 0 }}
EOF

log "Templates.yaml vytvořen"

# Vytvoření automations.yaml
cat > "$CONFIG_DIR/automations.yaml" << 'EOF'
- alias: "Automatický herní režim"
  trigger:
    - platform: state
      entity_id: binary_sensor.gaming_pc_status
      to: "on"
  action:
    - service: light.turn_off
      target:
        area_id: gaming_room
    - service: light.turn_on
      target:
        entity_id: light.gaming_ambient
      data:
        brightness: 30
        rgb_color: [0, 0, 255]
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.gaming_mode

- alias: "Upozornění na vysokou teplotu GPU"
  trigger:
    - platform: numeric_state
      entity_id: sensor.gaming_pc_gpu_temperature
      above: 80
  action:
    - service: notify.mobile_app_phone
      data:
        title: "⚠️ Vysoká teplota GPU"
        message: "Teplota grafické karty je {{ states('sensor.gaming_pc_gpu_temperature') }}°C"

- alias: "Automatické zálohování na NAS"
  trigger:
    - platform: time
      at: "02:00:00"
  condition:
    - condition: template
      value_template: "{{ states('sensor.nas_connection') == 'connected' }}"
  action:
    - service: backup.create
      data:
        name: "Automatická záloha {{ now().strftime('%Y-%m-%d') }}"
        password: !secret backup_password
EOF

log "Automations.yaml vytvořen"

# Vytvoření secrets.yaml template
cat > "$CONFIG_DIR/secrets.yaml" << 'EOF'
# ⚠️ UPRAVTE TENTO SOUBOR PODLE VAŠEHO NASTAVENÍ ⚠️

# Lokace
home_latitude: "50.0755"
home_longitude: "14.4378"
home_elevation: 200

# Databáze
recorder_db_url: "sqlite:////config/home-assistant_v2.db"

# MQTT
mqtt_username: "homeassistant"
mqtt_password: "silne_heslo_zmente_prosim"

# NAS
nas_ip: "192.168.1.100"
nas_username: "admin"
nas_password: "nas_heslo"

# Herní PC
gaming_pc_ip: "192.168.1.50"
gaming_pc_mac: "aa:bb:cc:dd:ee:ff"
gaming_pc_user: "gamer"
gaming_pc_password: "heslo"

# RetroPie
retropie_ip: "192.168.1.60"
retropie_mac: "ff:ee:dd:cc:bb:aa"

# Záloha
backup_password: "backup_heslo"

# API klíče
# openai_api_key: "your_key_here"
# steam_api_key: "your_steam_key"
EOF

log "Secrets.yaml template vytvořen - UPRAVTE HODNOTY!"

# Vytvoření UI Lovelace
cat > "$CONFIG_DIR/ui-lovelace.yaml" << 'EOF'
title: "Home Assistant - Auto Setup"
views:
  - title: "Přehled"
    icon: mdi:home
    cards:
      - type: glance
        title: "Stav systému"
        entities:
          - entity: sensor.cpu_temperature
            name: Teplota CPU
          - entity: sensor.ram_usage
            name: RAM
          - entity: sensor.disk_usage
            name: Disk
          - entity: sensor.day_phase
            name: Denní fáze

  - title: "Herní místnost"
    icon: mdi:gamepad-variant
    cards:
      - type: grid
        columns: 2
        cards:
          - type: button
            name: "Zapnout herní PC"
            tap_action:
              action: call-service
              service: script.turn_on_gaming_pc
            icon: mdi:power

          - type: button
            name: "Ranní rutina"
            tap_action:
              action: call-service
              service: script.wake_up_routine
            icon: mdi:weather-sunny

          - type: button
            name: "Večerní rutina"
            tap_action:
              action: call-service
              service: script.evening_routine
            icon: mdi:weather-night

          - type: button
            name: "Vyčistit systém"
            tap_action:
              action: call-service
              service: script.system_repair_cleanup
            icon: mdi:brush

      - type: entities
        title: "Stav herních systémů"
        entities:
          - entity: binary_sensor.gaming_pc_status
            name: Herní PC
          - entity: binary_sensor.minecraft_server_status
            name: Minecraft Server
          - entity: sensor.minecraft_players_online
            name: Hráči online
EOF

log "UI Lovelace vytvořen"

# Vytvoření package pro NAS
mkdir -p "$CONFIG_DIR/packages"
cat > "$CONFIG_DIR/packages/nas_setup.yaml" << 'EOF'
# NAS Setup Package
sensor:
  - platform: rest
    name: "NAS Storage Usage"
    resource: "http://!secret nas_ip:5000/api/storage"
    headers:
      Authorization: "Bearer !secret nas_api_token"
    value_template: "{{ value_json.used_percent }}"
    unit_of_measurement: "%"

binary_sensor:
  - platform: ping
    name: "NAS Connection"
    host: !secret nas_ip
    count: 3
    scan_interval: 60

backup:
  name: "Home Assistant Backup"
  backup_path: "/mnt/nas/backups"
  keep_days: 30
EOF

# Vytvoření package pro gaming
cat > "$CONFIG_DIR/packages/gaming_setup.yaml" << 'EOF'
# Gaming Setup Package
binary_sensor:
  - platform: ping
    name: "Gaming PC Status"
    host: !secret gaming_pc_ip
    count: 2
    scan_interval: 30

  - platform: ping
    name: "Minecraft Server Status"
    host: 127.0.0.1
    port: 25565
    scan_interval: 60

sensor:
  - platform: command_line
    name: "Minecraft Players Online"
    command: "docker exec minecraft-server rcon-cli list | cut -d' ' -f3 | cut -d'/' -f1"
    scan_interval: 30
    unit_of_measurement: "players"

shell_command:
  start_minecraft: "docker start minecraft-server"
  stop_minecraft: "docker stop minecraft-server"
  restart_minecraft: "docker restart minecraft-server"
  shutdown_gaming_pc: "net rpc shutdown -I !secret gaming_pc_ip -U !secret gaming_pc_user%'!secret gaming_pc_password'"
EOF

log "Balíčky vytvořeny"

# Vytvoření Docker compose pro herní servery
mkdir -p "$CONFIG_DIR/docker"
cat > "$CONFIG_DIR/docker/docker-compose-gaming.yml" << 'EOF'
version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
      MEMORY: "4G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
    volumes:
      - ./minecraft/data:/data
    networks:
      - gaming

  teamspeak-server:
    image: teamspeak:latest
    container_name: teamspeak-server
    restart: unless-stopped
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    environment:
      TS3SERVER_LICENSE: accept
    volumes:
      - ./teamspeak/data:/var/ts3server
    networks:
      - gaming

networks:
  gaming:
    driver: bridge
EOF

log "Docker compose soubory vytvořeny"

# Instalace HACS
log "Instaluji HACS..."
cd "$CONFIG_DIR"
mkdir -p custom_components
cd custom_components
if command -v wget &> /dev/null; then
    wget -O hacs.zip https://github.com/hacs/integration/releases/latest/download/hacs.zip
    unzip hacs.zip
    rm hacs.zip
elif command -v curl &> /dev/null; then
    curl -L -o hacs.zip https://github.com/hacs/integration/releases/latest/download/hacs.zip
    unzip hacs.zip
    rm hacs.zip
else
    log "❌ Nelze stáhnout HACS - nainstalujte jej manuálně"
fi

log "✅ HACS nainstalován"

# Restart Home Assistant
log "Restartuji Home Assistant..."
docker restart home-assistant

log "🎉 INSTALACE DOKONČENA!"
log "📋 DALŠÍ KROKY:"
log "   1. Upravte soubor $CONFIG_DIR/secrets.yaml podle vašeho nastavení"
log "   2. Počkejte na restart Home Assistant"
log "   3. V GUI spusťte skript 'system_repair_cleanup'"
log "   4. Přidejte integrace přes Nastavení → Zařízení a služby"
log "   5. Pro herní servery: cd $CONFIG_DIR/docker && docker-compose -f docker-compose-gaming.yml up -d"
log ""
log "📁 Záloha vytvořena v: $BACKUP_DIR"
log "🔧 Pro problémy zkontrolujte logy: docker logs -f home-assistant"
