camera:
  - platform: ffmpeg
    name: "Front Door Camera"
    input: "rtsp://user:password@192.168.1.10:554/stream"

  - platform: ffmpeg
    name: "Backyard Camera"
    input: "rtsp://user:password@192.168.1.11:554/stream"

binary_sensor:
  - platform: mqtt
    name: "Motion Front Door"
    state_topic: "home/camera/front_door/motion"
    device_class: motion
