#!/bin/bash
# Auto-sync, validate, commit, and push config changes
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMIT_MSG="${1:-Automated config sync from Home Assistant Suite}"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

cd "$REPO_ROOT"

echo "=== Autocommit: Config Sync & Commit ==="
echo "Timestamp: $TIMESTAMP"
echo ""

# Check git availability
if ! command -v git &>/dev/null; then
    echo "❌ Git is not installed"
    exit 1
fi

# Check if we're in a git repo
if ! git rev-parse --git-dir &>/dev/null; then
    echo "❌ Not in a git repository"
    exit 1
fi

# Sync configs
echo "1️⃣ Syncing configs..."
if [ -f "./scripts/sync_config.sh" ]; then
    ./scripts/sync_config.sh --force --validate || {
        echo "❌ Config sync failed"
        exit 1
    }
else
    echo "⚠️ sync_config.sh not found, skipping sync"
fi

echo ""
echo "2️⃣ Checking git status..."
git status

echo ""
echo "3️⃣ Staging changes..."

# Stage config changes
if [ -d "config/" ]; then
    git add config/ || true
fi

# Stage config source if changed
if [ -d "CONFIG/" ]; then
    git add CONFIG/ || true
fi

# Also stage docker-compose if changed
git add docker-compose.yml 2>/dev/null || true

# Check if there are changes to commit
if ! git diff --cached --quiet; then
    echo "📝 Changes staged:"
    git diff --cached --stat

    echo ""
    echo "4️⃣ Creating commit..."
    git commit -m "🤖 $COMMIT_MSG

Automated commit at $TIMESTAMP
- Config files synchronized
- YAML validation passed
- Docker compose checked

Generated by: autocommit.sh"

    echo ""
    echo "5️⃣ Pushing to remote..."
    
    # Get current branch
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    
    if git push origin "$BRANCH"; then
        echo "✅ Push successful to origin/$BRANCH"
    else
        echo "⚠️ Push failed. Trying to pull first..."
        git pull --rebase origin "$BRANCH"
        git push origin "$BRANCH"
        echo "✅ Push successful after rebase"
    fi

    echo ""
    echo "✅ Autocommit completed successfully!"
    echo "Commit: $(git log -1 --oneline)"
else
    echo "⏭️ No changes to commit"
    exit 0
fi

echo ""
echo "📊 Commit summary:"
git log -1 --stat
